名称： 带Grunt的NodeJS

在：
  推：
    分支：[        “主”        ]
  拉请求：
    分支：[           “主”           ]

工作：
  建造者：
    运行： ubuntu-latest

    战略：
      矩阵：
        节点版本：[ 14.x 、 16.x 、 18.x ]

    脚步：
    -使用： actions/checkout@v3

    -名称：使用Node.js $ {          {矩阵.节点版本}       }
      使用： actions/setup-node@v3
      和：
       }

    -名称：构建
      运行：|
        npm安装
        咕噜声
